### ISSUE TITLE
Limiting number of open pages

### ISSUE THREAD

**Issue by SamGalanakis** [scrapy-plugins/scrapy-playwright#59] opened 2022-02-18 14:52 UTC
I am running a scraper that opens a new page in playwright for certain types of links and would like to throttle these requests by say setting a max number of pages than can be open at any one time and adding them to a queue. How should I go about that? Currently it seems to open too many instances and overwhelms the cpu. Thanks in advance.

**Comment by samwillis** [comment] 2022-02-23 14:33
See: https://github.com/scrapy-plugins/scrapy-playwright/issues/6

I'm having success with the branch from that issue.

**Comment by elacuesta** [comment] 2022-02-27 17:30
Closing as duplicate of #6

**Closed by elacuesta** 2022-02-27 17:30 UTC
