### ISSUE TITLE
Loop back

### ISSUE THREAD

**Issue by scrapenetwork** [scrapy-plugins/scrapy-playwright#4] opened 2021-01-26 23:45 UTC
class AwesomeSpider(scrapy.Spider):
    name = "awesome"

    def start_requests(self):
        # GET request
        yield scrapy.Request("https://httpbin.org/get", meta={"playwright": True})
        # POST request
        yield scrapy.FormRequest(
            url="https://httpbin.org/post",
            formdata={"foo": "bar"},
            meta={"playwright": True},
        )

    def parse(self, response):
        # 'response' contains the page as seen by the browser
        yield {"url": response.url}
#finished,loop back

        

Hey im unfamiliar how to loop back on this with this feature.
in your example say , how would you loop back to def parse ? Im familiar with scrapy features but that way is not working

**Comment by elacuesta** [comment] 2021-01-30 13:53
I'm not sure I understand what you mean, could you elaborate?

**Comment by scrapenetwork** [comment] 2021-01-30 21:00
> I'm not sure I understand what you mean, could you elaborate?

First of all amazing plugin :)
Second, what i mean example in scrapy:

def parse(self, response):
    # 'response' contains the page as seen by the browser
    yield {"url": response.url}
#too loop back to def parse 
yield scrapy request(etc etc...)



This will parse (def parse()) and then loop back and to def parse 


I am unable to find a way to loop back to a function with this plugin if you’re able to explain please.

**Comment by elacuesta** [comment] 2021-02-08 18:09
The main idea of this project is that everything works as users would expect in Scrapy. To that end, the user agent is taken from the [`USER_AGENT`](https://docs.scrapy.org/en/latest/topics/settings.html#user-agent) setting, cookies processed by the built-in [`CookiesMiddleware`](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.cookies.CookiesMiddleware) and headers are taken from the Scrapy request before sending the request with the browser.

Please, do share any additional issues you may have here.

Should we close this specific issue?

**Comment by elacuesta** [comment] 2021-02-08 19:06
Regarding proxies, you can pass a `proxy` dictionary via the `PLAYWRIGHT_LAUNCH_OPTIONS` setting, it will be passed to [`BrowserType.launch`](https://playwright.dev/python/docs/api/class-browsertype#browser_typelaunchkwargs):

```python
# settings.py
PLAYWRIGHT_LAUNCH_OPTIONS = {
    "proxy": {
        "server": "http://myproxy.com:3128",
        "username": "foo",
        "password": "bar",
    },
}
```

I'm experimenting with this myself, hopefully I'll be able to update the docs and add some examples soon.

**Comment by scrapenetwork** [comment] 2021-02-09 01:49
> The main idea of this project is that everything works as users would expect in Scrapy. To that end, the user agent is taken from the [`USER_AGENT`](https://docs.scrapy.org/en/latest/topics/settings.html#user-agent) setting, cookies processed by the built-in [`CookiesMiddleware`](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.cookies.CookiesMiddleware) and headers are taken from the Scrapy request before sending the request with the browser.
> 
> Please, do share any additional issues you may have here.
> 
> Should we close this specific issue?

Thanks for taking the time to reply.

- if inputting the ua the scrapy way (settings or what ever way works for you from scrapy request)works. The issue is the url(page) is still receiving the chromium ua. I dont think the request is being sent with the ua being placed.
- Im currently trying to debug an issue with no available log errors, after a few mins (5-10)just hangs on crawled 0 pages 0items . I will continue to try and debug to try to atleast get a logged error somewhere.
- Proxies, i will try and as mentioned above and share the results, thxs


Fanatic plugin keep up the great work!

**Comment by elacuesta** [comment] 2021-02-09 14:00
Could you share a piece of code to reproduce the User Agent issue? For instance, I'm getting the expected result with the following snippet, either defining the user agent in `settings.py` or in `Spider.custom_settings`:

```python
import scrapy

class HttpbinSpider(scrapy.Spider):
    name = "httpbin"
    custom_settings = {
        "USER_AGENT": "I'm a browser",
    }

    def start_requests(self):
        yield scrapy.Request("https://httpbin.org/headers", meta={"playwright": True})

    def parse(self, response):
        print(response.text)
```

```
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
    "Accept-Encoding": "gzip, deflate", 
    "Accept-Language": "en", 
    "Cache-Control": "no-cache", 
    "Host": "httpbin.org", 
    "Pragma": "no-cache", 
    "Sec-Fetch-Dest": "document", 
    "Sec-Fetch-Mode": "navigate", 
    "Sec-Fetch-Site": "none", 
    "Sec-Fetch-User": "?1", 
    "User-Agent": "I'm a browser", 
    "X-Amzn-Trace-Id": "Root=x-xxxxxxx-xxxxxxxxxxxxxxxxxxx"
  }
}
</pre></body></html>
```

In fact, if I don't specify a custom user agent, I see `Scrapy/2.4.1 (+https://scrapy.org)`, Scrapy's default, which is also expected.

**Comment by scrapenetwork** [comment] 2021-02-10 02:25
I was checking the ua via the browser

i am just using simple code snippets just like the one you pasted above.

proxies is indeed working fine, wondering 

- possible to move and set it per request(proxie)?
- Click page coroutine works perfectly, and gets correct response, wondering what would be the similar to setting / waiting(time.sleep) and getting the response from the page/browsers redirect.
- A way to debug playwright logs, i have settings on (able to see scrapys logs), also tried debug=pw:api in settings and script.
- in your read me, The browser launch urls along with others has moved, error 404. Seems maybe because playwrights docs has changed as it has updated.


Again thxs for reply, keep up the amazing work

**Comment by elacuesta** [comment] 2021-02-22 18:33
> * possible to move and set it per request(proxie)?

Not possible at the moment. Upstream `playwright-python` allows to set a proxy per context, but currently this library works with a single context. I wanted to allow for multiple contexts here, but I need to think about a good API to handle it

> * Click page coroutine works perfectly, and gets correct response, wondering what would be the similar to setting / waiting(time.sleep) and getting the response from the page/browsers redirect.

Not sure I understand, could you elaborate?

> * A way to debug playwright logs, i have settings on (able to see scrapys logs), also tried debug=pw:api in settings and script.

Currently, you can run the command adding `DEBUG=pw:api` at the beggining: `DEBUG=pw:api scrapy crawl myspider`

> * in your read me, The browser launch urls along with others has moved, error 404. Seems maybe because playwrights docs has changed as it has updated.

Updated, thanks

> * Away to manually pre set the cookies , page.cookies() does not work
> (Example:
> Yield scrapt request(...cookies=cookies,meta={playwright...)

The [`Request.cookies`](https://docs.scrapy.org/en/latest/topics/request-response.html#scrapy.http.Request) parameter works for this, since every request follows the regular Scrapy flow and is processed by the `CookiesMiddleware`. See the newly added `examples/cookies.py` file for an example.
 
> * a way to handle playwright errors and handle them, timeout errors , i am not sure how to properly handle requests errors from playwright

All exceptions are handled by Scrapy itself, you can use define a [downloader middleware](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html) with a `process_spider_exception` method. See the newly added `examples/exception.py` file for an example.

**Comment by scrapenetwork** [comment] 2021-02-23 07:29
No problem either way successful plugin.

if you can please update if & when multi context is handled here.

one other random issue with firefox headless 
Keep coming across this error.

================================================================================
“firefox” browser was not found.
Please complete Playwright installation via running

  “python -m playwright install”

================================================================================



Its installed and dont seem to understand why this pings up thxs

**Comment by scrapenetwork** [comment] 2021-02-23 14:00
When running headless firefox


error:
================================================================================
“firefox” browser was not found.
Please complete Playwright installation via running

  “python -m playwright install”

================================================================================



all other browsers are working, including firefox headless false.
Error seems to happen randomly, after retrying the script several times it works.

Not sure I understand, could you elaborate?
- what i mean, example, url is requested, the page makes a redirect from the url, waits a few seconds and then again redirects to the requested site. Ive tried a few different ways, but unable to receive/print the response from the wanted redirected page. Im always getting the response from the incorrect redirect.


Everything else as noted is working perfect, appreciate the examples

**Comment by elacuesta** [comment] 2021-02-23 14:58
It seems to me like there's a mismatch in the versions in the latest Playwright version. For instance, tests for this package are failing because [chromium 833159 is installed](https://github.com/scrapy-plugins/scrapy-playwright/runs/1962125389?check_suite_focus=true#step:5:18) but [844399 is used](https://github.com/scrapy-plugins/scrapy-playwright/runs/1962125389?check_suite_focus=true#step:6:205).
In the meantime, you can be explicit by using `executablePath` (snake case `executable_path` in the latest `0.0.3` version) in `PLAYWRIGHT_LAUNCH_OPTIONS`.

**Comment by scrapenetwork** [comment] 2021-02-24 11:51
> It seems to me like there's a mismatch in the versions in the latest Playwright version. For instance, tests for this package are failing because [chromium 833159 is installed](https://github.com/scrapy-plugins/scrapy-playwright/runs/1962125389?check_suite_focus=true#step:5:18) but [844399 is used](https://github.com/scrapy-plugins/scrapy-playwright/runs/1962125389?check_suite_focus=true#step:6:205).
> In the meantime, you can be explicit by using `executablePath` (snake case `executable_path` in the latest `0.0.3` version) in `PLAYWRIGHT_LAUNCH_OPTIONS`.

Sorry for the noobie questions,but are you able to provide an example on mac?

Shows here on mac its located
/users/.../library/caches/ms-playwright/firefox-1221/firefox

used a few strings on executable path, including the nightly.app with failed to launch browser.
Again this issue is only on headless , with this false, its able to find browser with 0 issues.

**Comment by elacuesta** [comment] 2021-02-24 13:05
Firefox on macOS should be located under `/Applications/Firefox.app/Contents/MacOS/firefox`. However, I'd suggest you to try again in a clean environment (i.e. reinstall `playwright`), since tests are green again and scripts are working with the bundled browsers.

**Comment by scrapenetwork** [comment] 2021-03-22 22:37
Please update thread

if / when you are able to control the launch settings in the meta appreciate it :)

**Comment by elacuesta** [comment] 2021-03-23 00:02
I'm not sure I understand correctly, but if you mean passing new options to [`BrowserType.launch`](https://playwright.dev/python/docs/api/class-browsertype#browser_typelaunchkwargs) via the Scrapy `Request.meta`, it cannot be done. There is currently only one browser instance per crawl, launched at the beginning; by the time requests are processed it's already been launched.

**Comment by scrapenetwork** [comment] 2021-03-30 16:31
Yes in deed

need to be able to use middlewares such as proxies ones

**Comment by elacuesta** [comment] 2021-04-10 23:33
This issue has gone far beyond its original purpose. Please open a new one if you have any specific question or request.

**Closed by elacuesta** 2021-04-10 23:33 UTC
