### ISSUE TITLE
KeyError: 'playwright_page' 

### ISSUE THREAD

**Issue by Nekender02** [scrapy-plugins/scrapy-playwright#272] opened 2024-05-24 20:48 UTC
```
async def errback_close_page(self, failure):
        page = failure.request.meta["playwright_page"]
        await page.close()

def start_requests(self):
        if not self.start_urls and hasattr(self, "start_url"):
            raise AttributeError(
                "Crawling could not start: 'start_urls' not found "
                "or empty (but found 'start_url' attribute instead, "
                "did you miss an 's'?)"
            )
        for url in self.start_urls:
            npo = self.npos[url]
            logging.info("### crawl: %s", url)
            yield scrapy.Request(
                url, callback=self.my_parse, dont_filter=True,meta={"playwright": True, "playwright_include_page": True, 'start_time': datetime.utcnow()}, cb_kwargs={"npo": npo},errback= self.errback_close_page
                
            )
```

can anyone please explain why am I getting this error and how can I fix this?

Traceback (most recent call last): File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1065, in adapt extracted = result.result() File "/home/ec2-user/SageMaker/xx", line 50, in errback_close_page page = failure.request.meta["playwright_page"] KeyError: 'playwright_page'

**Comment by elacuesta** [comment] 2024-05-25 19:08
It could be that you're not correctly [activating the download handler](https://github.com/scrapy-plugins/scrapy-playwright?tab=readme-ov-file#activation). Are you seeing log lines from the `scrapy-playwright` logger? i.e. something like:
```
2024-05-25 16:06:00 [scrapy-playwright] INFO: Starting download handler
2024-05-25 16:06:05 [scrapy-playwright] INFO: Launching browser chromium
2024-05-25 16:06:05 [scrapy-playwright] INFO: Browser chromium launched
```

**Comment by Nekender02** [comment] 2024-05-26 15:44
Yes ,
![image](https://github.com/scrapy-plugins/scrapy-playwright/assets/165470106/082b5ea0-2069-42f8-bfbf-36fb70ed56f3)

i have added download handlers in my settings.py 
DOWNLOAD_HANDLERS = {
    "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
    "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
}

**Comment by Nekender02** [comment] 2024-05-29 00:25
Any updates ? still not able to solve the KeyError: 'playwright_page'

**Comment by elacuesta** [comment] 2024-05-29 02:07
There is not enough information to reproduce. Please refer to https://github.com/scrapy-plugins/scrapy-playwright?tab=readme-ov-file#reporting-issues.

**Comment by jiaohu** [comment] 2024-06-02 10:50
**More Detail**
I want to use my spider to get info from `https://www.manamana.net/exploreauth`, I write code obey the sample, but get this error too.
And then I translate my code as this [](https://github.com/scrapy-plugins/scrapy-playwright?tab=readme-ov-file#reporting-issues)
Then I get the picture
![example](https://github.com/scrapy-plugins/scrapy-playwright/assets/13608671/89ff2dac-8085-47ed-b618-384d03e8a993)
But I want to get this
![image](https://github.com/scrapy-plugins/scrapy-playwright/assets/13608671/5155892e-6d57-4616-9731-e2f5a1f0f5d8)
![image](https://github.com/scrapy-plugins/scrapy-playwright/assets/13608671/51eb7404-0dc3-407e-ae0c-c3e48f9a304a)

The reason is that **there are several seconds** between this two kind, I think there are some bug for `playwright` to render the page which is dynamic

**Comment by elacuesta** [comment] 2024-06-02 17:28
> The reason is that there are several seconds between this two kind, I think there are some bug for playwright to render the page which is dynamic

This is precisely why the docs suggest trying standalone Playwright for debugging. You are not getting the result you expect with standalone Playwright, so the problem is not caused by scrapy-playwright.

This is not a bug though. I'd recommend ensuring the DOM is fully loaded before returning the result by passing `wait_until="domcontentloaded"` to [Page.goto](https://playwright.dev/python/docs/api/class-page#page-goto) in standalone Playwright or via the [playwright_page_goto_kwargs](https://github.com/scrapy-plugins/scrapy-playwright?tab=readme-ov-file#playwright_page_goto_kwargs) Request meta key scrapy-playwright.

> but get this error too

If by "this error" you mean the originally reported error about the a KeyError on the `playwright_page` meta key, there is no Scrapy code in your to work with.

**Comment by Nekender02** [comment] 2024-06-02 20:53
The KeyError: 'playwright_page' , I solved it my declaring errback inside meta.

```
yield scrapy.Request(
                url, callback=self.my_parse, dont_filter=True, meta=dict(playwright=True, playwright_include_page=True, start_time=datetime.utcnow(), errback=self.errback_close_page), cb_kwargs={"npo": npo},

            )
```

**Comment by elacuesta** [comment] 2024-06-08 21:11
The failing requests have a referrer header, they are not coming from your `start_requests` method. You haven't shared a full spider, I suspect those specific requests do not have `playwright_include_page=True` in their meta. 
I'm closing this, if you're still having trouble and want to reopen the issue you need to include a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) as instructed in the [Reporting issues](https://github.com/scrapy-plugins/scrapy-playwright?tab=readme-ov-file#reporting-issues) section.

**Closed by elacuesta** 2024-06-08 21:11 UTC
Labels: needs more info

**Comment by Nekender02** [comment] 2024-06-24 17:05
So on further analysis I was able to pin point to exact error , Forbidden by robot.txt is causing the crawler to freeze. The issue is failure requests that are forbidden by robot.txt has no playwright_page associated to them, therefore i am not able to close them using page.close which is causing my crawler to freeze where page = failure.request.meta["playwright_page"]
Note 

- My crawler works absolutely fine when ROBOTSTXT_OBEY is set to false, but I want to keep it true.

Here is the minimal reproduceable code 
```
import re
import scrapy
import logging
from bs4 import BeautifulSoup
from datetime import datetime
from urllib.parse import urlparse
from scrapy.linkextractors import LinkExtractor

emails_re = re.compile(r"\b([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})\b", re.IGNORECASE)

class GrantsSpider(scrapy.Spider):
    name = "npos"
    reported_links = []
    link_extractor = LinkExtractor(unique=True)
    npos = {}

    async def errback_close_page(self, failure):
        logging.error(f"Error processing {failure.request.url}: {repr(failure)}")
        page = failure.request.meta.get("playwright_page")
        if page:
            await page.close()
            await page.context.close()
            logging.info(f"Page {page} closed on error")

    def start_requests(self):
        url = 'https://www.guidestar.org/profile/26-1700710'
        npo = {"ein": "26-1700710", "name": "Example NPO", "type": "Nonprofit"}
        logging.info(f"### crawl: {url}")
        yield scrapy.Request(
            url, callback=self.my_parse, dont_filter=True,
            meta={"playwright": True, "playwright_include_page": True, 'dont_redirect': True},
            cb_kwargs={"npo": npo},
            errback=self.errback_close_page
        )

    async def my_parse(self, response, npo):
        page = response.meta["playwright_page"]
        self.reported_links.append(response.url)
        try:
            _ = response.text
        except AttributeError as exc:
            logging.debug(f"Skipping {response.url}: {exc}")
            await page.close()
            return

        body, match = self.is_page(response, None)
        for email in emails_re.findall(body):
            yield {
                "ein": npo["ein"],
                "name": npo["name"],
                "type": npo["type"],
                "msg": "link-email",
                "match": email,
                "text": email,
                "url": response.url,
                "timestamp": datetime.utcnow(),
            }

        for link in response.xpath("//a"):
            href = link.xpath("./@href").get()

            if not href or href.startswith("javascript:") or href.startswith("#"):
                continue

            if not href.startswith("http"):
                href = response.urljoin(href)

            if href not in self.reported_links:
                yield scrapy.Request(
                    href, callback=self.my_parse,
                    meta={"playwright": True, "playwright_include_page": True, 'dont_redirect': True},
                    cb_kwargs={"npo": npo},
                    errback=self.errback_close_page
                )

        await page.close()

    def is_page(self, response, re_expression):
        sel = scrapy.Selector(response)
        sel.xpath("//head").remove()
        sel.xpath("//header").remove()
        # sel.xpath("//footer").remove()
        sel.xpath("//navbar").remove()
        sel.xpath("//a").remove()
        body = sel.get()
        bs_doc = BeautifulSoup(body, features="lxml").get_text(strip=True, separator=" ")
        if not re_expression:
            return bs_doc, None
        if re_expression.search(bs_doc):
            matches = list(set(list(re.findall(re_expression, bs_doc))[0]))
            if "" in matches:
                matches.remove("")
            return bs_doc, matches
        return None, None
```

**Comment by elacuesta** [comment] 2024-06-25 17:07
Sounds reasonable, from a quick look I think [this](https://github.com/scrapy/scrapy/blob/2.11/scrapy/downloadermiddlewares/robotstxt.py#L63) is the Scrapy exception you're getting.

I'd say that's expected behavior though, you'll just need to check in your errback if there is actually a page to close before attempting to close it. Furthermore, unless your actual spider is bigger and what you posted is a reduced example, I'd recommend you ask yourself if it's really necessary to pass `playwright_include_page=True`. You don't seem to be interacting with the page besides closing it, you might be better of not passing `playwright_include_page` and allowing the handler to close the page on its own. See also [these docs](https://github.com/scrapy-plugins/scrapy-playwright?tab=readme-ov-file#receiving-page-objects-in-callbacks).

**Comment by Nekender02** [comment] 2024-06-26 08:42
The actually spider is much bigger and this is just a minimal code of it. I was able to solve this by changing my errback method a bit 

```
async def errback_close_page(self, failure):
        self.logger.error(f'Error processing page: {repr(failure)}')
        if "playwright_page" in failure.request.meta:
            page = failure.request.meta["playwright_page"]
            if page:
                await page.close()
                self.logger.info(f"Closed page due to error: {page}")
        raise CloseSpider(reason='Forbidden by robots.txt')
```

**Comment by Nekender02** [comment] 2024-06-26 20:40
Hi Eugenio, even after making the changes I am still facing the issue where my spider gets stuck even if its closed 

```
{'BOT_NAME': 'test',
 'CLOSESPIDER_ITEMCOUNT': 300,
 'CLOSESPIDER_PAGECOUNT': 300,
 'CLOSESPIDER_TIMEOUT': 300,
 'CONCURRENT_REQUESTS': 8,
 'CONCURRENT_REQUESTS_PER_DOMAIN': 4,
 'CONCURRENT_REQUESTS_PER_IP': 4,
 'COOKIES_ENABLED': False,
 'DEPTH_LIMIT': 2,
 'DEPTH_PRIORITY': 1,
 'DNS_TIMEOUT': 3,
 'DOWNLOAD_DELAY': 0.3,
 'DOWNLOAD_TIMEOUT': 120,
 'FEED_EXPORT_ENCODING': 'utf-8',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'myConfig.spiders',
 'REQUEST_FINGERPRINTER_IMPLEMENTATION': '2.7',
 'RETRY_ENABLED': False,
 'ROBOTSTXT_OBEY': True,
 'SCHEDULER_DISK_QUEUE': 'scrapy.squeues.PickleFifoDiskQueue',
 'SCHEDULER_MEMORY_QUEUE': 'scrapy.squeues.FifoMemoryQueue',
 'SPIDER_MODULES': ['myConfig.spiders'],
 'TELNETCONSOLE_ENABLED': False,
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor',
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'}
2024-06-26 20:28:06 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.closespider.CloseSpider',
 'scrapy.extensions.logstats.LogStats']
2024-06-26 20:28:06 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'myConfig.middlewares.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware']
2024-06-26 20:28:06 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2024-06-26 20:28:06 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2024-06-26 20:28:06 [scrapy.core.engine] INFO: Spider opened
2024-06-26 20:28:07 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
#### Run crawlers 25040-25040
2024-06-26 20:28:07 [scrapy-playwright] INFO: Starting download handler
2024-06-26 20:28:07 [scrapy-playwright] INFO: Starting download handler
2024-06-26 20:28:12 [root] INFO: ### crawl: http://www.trinityschooloftexas.com
2024-06-26 20:28:12 [scrapy-playwright] INFO: Launching browser chromium
2024-06-26 20:28:12 [scrapy-playwright] INFO: Browser chromium launched
2024-06-26 20:28:18 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.trinityschooloftexas.com> (referer: None)
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/utils/defer.py", line 276, in aiter_errback
    yield await it.__anext__()
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/utils/python.py", line 360, in __anext__
    return await self.data.__anext__()
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/utils/python.py", line 341, in _async_chain
    async for o in as_async_generator(it):
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/utils/asyncgen.py", line 14, in as_async_generator
    async for r in it:
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/utils/python.py", line 360, in __anext__
    return await self.data.__anext__()
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/utils/python.py", line 341, in _async_chain
    async for o in as_async_generator(it):
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/utils/asyncgen.py", line 14, in as_async_generator
    async for r in it:
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/core/spidermw.py", line 118, in process_async
    async for r in iterable:
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/spidermiddlewares/offsite.py", line 31, in process_spider_output_async
    async for r in result or ():
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/core/spidermw.py", line 118, in process_async
    async for r in iterable:
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/spidermiddlewares/referer.py", line 355, in process_spider_output_async
    async for r in result or ():
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/core/spidermw.py", line 118, in process_async
    async for r in iterable:
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/spidermiddlewares/urllength.py", line 30, in process_spider_output_async
    async for r in result or ():
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/core/spidermw.py", line 118, in process_async
    async for r in iterable:
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/spidermiddlewares/depth.py", line 35, in process_spider_output_async
    async for r in result or ():
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/core/spidermw.py", line 118, in process_async
    async for r in iterable:
  File "/home/ec2-user/SageMaker/grant-crawler/myConfig/spiders/npos.py", line 75, in my_parse
    yield scrapy.Request(
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/http/request/__init__.py", line 93, in __init__
    self._set_url(url)
  File "/home/ec2-user/SageMaker/grant-crawler/venv/lib/python3.10/site-packages/scrapy/http/request/__init__.py", line 143, in _set_url
    raise ValueError(f"Missing scheme in request url: {self._url}")
ValueError: Missing scheme in request url: mailto:info@trinityschooloftexas.com
2024-06-26 20:28:18 [scrapy-playwright] INFO: Launching browser chromium
2024-06-26 20:28:19 [scrapy-playwright] INFO: Browser chromium launched
2024-06-26 20:29:07 [scrapy.extensions.logstats] INFO: Crawled 3 pages (at 3 pages/min), scraped 0 items (at 0 items/min)
2024-06-26 20:30:07 [scrapy.extensions.logstats] INFO: Crawled 3 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
^C2024-06-26 20:30:22 [scrapy.crawler] INFO: Received SIGINT, shutting down gracefully. Send again to force 
2024-06-26 20:30:22 [scrapy.core.engine] INFO: Closing spider (shutdown)
^C2024-06-26 20:30:22 [scrapy.crawler] INFO: Received SIGINT twice, forcing unclean shutdown
#### End crawlers 25040-25040
execution time: 137.11071705818176
^CScript execution complete.
(venv) sh-4.2$ ./run.sh
Starting script execution...
en_core_web_sm is already downloaded.
2024-06-26 20:30:36 [scrapy.utils.log] INFO: Scrapy 2.9.0 started (bot: test)
2024-06-26 20:30:36 [scrapy.utils.log] INFO: Versions: lxml 4.9.2.0, libxml2 2.9.14, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.1, Twisted 22.10.0, Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0], pyOpenSSL 23.2.0 (OpenSSL 3.1.1 30 May 2023), cryptography 41.0.1, Platform Linux-5.10.215-203.850.amzn2.x86_64-x86_64-with-glibc2.26
#### Create crawler for 25040: www.trinityschooloftexas.com
2024-06-26 20:30:37 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'test',
 'CLOSESPIDER_ITEMCOUNT': 300,
 'CLOSESPIDER_PAGECOUNT': 300,
 'CLOSESPIDER_TIMEOUT': 300,
 'CONCURRENT_REQUESTS': 8,
 'CONCURRENT_REQUESTS_PER_DOMAIN': 4,
 'CONCURRENT_REQUESTS_PER_IP': 4,
 'COOKIES_ENABLED': False,
 'DEPTH_LIMIT': 2,
 'DEPTH_PRIORITY': 1,
 'DNS_TIMEOUT': 3,
 'DOWNLOAD_DELAY': 0.3,
 'DOWNLOAD_TIMEOUT': 120,
 'FEED_EXPORT_ENCODING': 'utf-8',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'myConfig.spiders',
 'REQUEST_FINGERPRINTER_IMPLEMENTATION': '2.7',
 'RETRY_ENABLED': False,
 'ROBOTSTXT_OBEY': True,
 'SCHEDULER_DISK_QUEUE': 'scrapy.squeues.PickleFifoDiskQueue',
 'SCHEDULER_MEMORY_QUEUE': 'scrapy.squeues.FifoMemoryQueue',
 'SPIDER_MODULES': ['myConfig.spiders'],
 'TELNETCONSOLE_ENABLED': False,
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor',
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'}
2024-06-26 20:30:37 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.closespider.CloseSpider',
 'scrapy.extensions.logstats.LogStats']
2024-06-26 20:30:37 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'myConfig.middlewares.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware']
2024-06-26 20:30:37 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2024-06-26 20:30:37 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2024-06-26 20:30:37 [scrapy.core.engine] INFO: Spider opened
2024-06-26 20:30:38 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
#### Run crawlers 25040-25040
2024-06-26 20:30:38 [scrapy-playwright] INFO: Starting download handler
2024-06-26 20:30:38 [scrapy-playwright] INFO: Starting download handler
2024-06-26 20:30:43 [root] INFO: ### crawl: http://www.trinityschooloftexas.com
2024-06-26 20:30:43 [scrapy-playwright] INFO: Launching browser chromium
2024-06-26 20:30:43 [scrapy-playwright] INFO: Browser chromium launched
2024-06-26 20:30:49 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.trinityschooloftexas.com> (referer: None)
2024-06-26 20:30:49 [scrapy-playwright] INFO: Launching browser chromium
2024-06-26 20:30:50 [scrapy-playwright] INFO: Browser chromium launched
2024-06-26 20:31:38 [scrapy.extensions.logstats] INFO: Crawled 3 pages (at 3 pages/min), scraped 0 items (at 0 items/min)
2024-06-26 20:32:38 [scrapy.extensions.logstats] INFO: Crawled 3 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2024-06-26 20:33:38 [scrapy.extensions.logstats] INFO: Crawled 3 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2024-06-26 20:34:38 [scrapy.extensions.logstats] INFO: Crawled 3 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2024-06-26 20:35:38 [scrapy.core.engine] INFO: Closing spider (closespider_timeout)
2024-06-26 20:35:38 [scrapy.extensions.logstats] INFO: Crawled 3 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2024-06-26 20:36:38 [scrapy.extensions.logstats] INFO: Crawled 3 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2024-06-26 20:37:38 [scrapy.extensions.logstats] INFO: Crawled 3 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
```


I am linking the GitHub repo with minimal code which will help you replicate the issue , any help would be appreciated. Thanks
https://github.com/nekender/Playwright_Issue/

**Comment by Nekender02** [comment] 2024-06-28 09:07
Hi @elacuesta , did you get the time to have look ?

**Comment by elacuesta** [comment] 2024-06-28 14:21
Is not clear to me what the issue is in your last report. Furthermore, what you shared is not minimal: there are multiple files, middlewares, regex processing, selector manipulation, HTML parsing with BeautifulSoup, etc, none of which are likely to be related to what you report. It is often the case that developers understand and solve issues on their own during the process of distilling a program down to the bare minimum necessary to reproduce a problem.
So far this issue doesn't contain any reproducible bug report, it has always been a support matter and there are better resources to handle those (e.g. [the scrapy-playwright tag at StackOverflow](https://stackoverflow.com/questions/tagged/scrapy-playwright)).
