### ISSUE TITLE
How should I use scrapy-playwright without downloading images?

### ISSUE THREAD

**Issue by phongtnit** [scrapy-plugins/scrapy-playwright#51] opened 2022-01-25 06:56 UTC
Hi,

Could anyone help me to use scrapy-playwright without downloading images?

Thanks for your support,

**Comment by elacuesta** [comment] 2022-01-26 03:06
This seems like a duplicate of #26, please reopen with more info if you don't agree.

**Closed by elacuesta** 2022-01-26 03:06 UTC

**Comment by lime-n** [comment] 2022-02-28 17:38
> This seems like a duplicate of #26, please reopen with more info if you don't agree.

I have a question on this.

I have followed the example you provided in the answer to that thread, and from my initial thought I imagined no images would be downloaded, i.e.  I would not get any response/requests sent to .jpeg attachements.

Here's the output I get:
```
 'playwright/context_count': 1,
 'playwright/page_count': 1,
 'playwright/page_count/closed': 1,
 'playwright/request_count': 30,
 'playwright/request_count/method/GET': 30,
 'playwright/request_count/navigation': 1,
 'playwright/request_count/resource_type/document': 1,
 'playwright/request_count/resource_type/font': 1,
 'playwright/request_count/resource_type/image': 20, #<- why are requests sent to images?
 'playwright/request_count/resource_type/script': 5,
 'playwright/request_count/resource_type/stylesheet': 3,
```

Perhaps I have misunderstood what context actually do - If I wanted no requests/responses sent/received from images how would I accomplish this or is this the same as saying 'without downloading images'.

**Comment by elacuesta** [comment] 2022-02-28 21:02
Only #63 should be considered "in progress". That said, it's probably going to keep showing requests like that in the stats, because it relies on aborting requests caught by the `Page.route` method, while these stats are incremented via the `request` event. The `playwright/request_count/blocked` stat and lack of `playwright/request_count/resource_type/image` should be indicatives that it's working.

**Comment by lime-n** [comment] 2022-03-01 10:02
> Only #63 should be considered "in progress". That said, it's probably going to keep showing requests like that in the stats, because it relies on aborting requests caught by the `Page.route` method, while these stats are incremented via the `request` event. The `playwright/request_count/blocked` stat and lack of `playwright/request_count/resource_type/image` should be indicatives that it's working.

`playwright/request_count/blocked` is this a new feature? I cannot seem to get this output. If I understand the increment correctly, the `resource_types` should only increment those requests with a response `200`? Therefore, the images have received a response - wouldn't it save resources to prevent these responses altogether?

**Comment by lime-n** [comment] 2022-03-01 11:51
I have checked the update you have made, and thank you for taking the time to make these amendments. I have updated my `handler.py` with the latest to include the changes and ran the script above. I still do not get any `request_count/blocked` with the approach above, here's the output console:

```
{'downloader/request_bytes': 222,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 51182,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 6.398593,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2022, 3, 1, 11, 49, 40, 883833),
 'item_scraped_count': 1,
 'log_count/DEBUG': 64,
 'log_count/INFO': 44,
 'memusage/max': 119721984,
 'memusage/startup': 119721984,
 'playwright/context_count': 1,
 'playwright/page_count': 1,
 'playwright/page_count/closed': 1,
 'playwright/page_count/max_concurrent': 1,
 'playwright/request_count': 30,
 'playwright/request_count/method/GET': 30,
 'playwright/request_count/navigation': 1,
 'playwright/request_count/resource_type/document': 1,
 'playwright/request_count/resource_type/font': 1,
 'playwright/request_count/resource_type/image': 20,
 'playwright/request_count/resource_type/script': 5,
 'playwright/request_count/resource_type/stylesheet': 3,
 'playwright/response_count': 30,
 'playwright/response_count/method/GET': 30,
 'playwright/response_count/resource_type/document': 1,
 'playwright/response_count/resource_type/font': 1,
 'playwright/response_count/resource_type/image': 20,
 'playwright/response_count/resource_type/script': 5,
 'playwright/response_count/resource_type/stylesheet': 3,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2022, 3, 1, 11, 49, 34, 485240)}
```

**Comment by elacuesta** [comment] 2022-03-01 14:59
That's correct, the `configure_context` approach was very much experimental (there wasn't even a PR). There are still some details to think about with the new approach as well, but the following should be enough for now to block requests based on resource type
```python
PLAYWRIGHT_ACCEPT_REQUEST_PREDICATE = lambda req: req.resource_type not in ("image", "script")
```

**Comment by lime-n** [comment] 2022-03-01 18:27
Thank you for the implementation - I agree, there's still more creative ideas for it's implementation. An additional one may be the following:
1. To substantiate in the meta arguments, or handlers when to activate the settings argument for `PLAYWRIGHT_ACCEPT_REQUEST_PREDICATE`. 

For the following reason:
If I am using `PageCoroutine` to log into a website I cannot remove some resource types as otherwise I won't have access to the login. After accessing the site, I may be making further requests to another domain belonging to the site. It may be useful to access the  `PLAYWRIGHT_ACCEPT_REQUEST_PREDICATE` here. Although, making this multifunctional, for example - 

```
meta = {
    'playwright_accept_request_predicate': {
        'activate':True,
        'position': 1
            }
}
```
`activate` would describe whether to activate the settings for `PLAYWRIGHT_ACCEPT_REQUEST_PREDICATE` for the requests in that method. Whereas, position would denote the following:

```
PLAYWRIGHT_ACCEPT_REQUEST_PREDICATE = lambda req: req.resource_type not in ("image", "script")
```
The position of the `resource_type`. However, there may be a few technical issues with this. Alternatively, we could include:

```
meta = {
    'playwright_accept_request_predicate': {
        'activate':True,
        'group': 'resource_type'
        'position': 1
            }
}
```

This makes things slightly more complex - however, what this would represent is the following:
The `position` argument is already pre-determined by the position of resource_types in the source code. For example, if resource types take the following list sequence: ```request.resource_type  = ['xhr', 'JS' ...]``` then we pick on this position.

Then the following will denote:

```
meta = {
    'playwright_accept_request_predicate': {
        'activate':True,
        'group': 'resource_type'
        'position': False
            }
}
```
All the resource types are included.

**Comment by lime-n** [comment] 2022-03-02 13:51
On addition to the above; there's also a need to include the route handle, as such:
```
meta = {
    'playwright_accept_request_predicate': {
        'activate':True,
        'handle': 'fulfill'
        'group': 'resource_type'
        'position': False
            }
}
```

Where, the `handle` determines how to handle the route. Furthermore, I have noticed that `route.request` provides the request to be aborted.

Alternatively, I was thinking how functional would `route.request` be in the given case; The idea I had was that we can abort all request urls when their response is not <200>. Not sure how much of an impact this has on the scrapy context and the side-effects of running this, however it may prevent issues like `time-outs`.

@elacuesta  your thoughts?

**Comment by elacuesta** [comment] 2022-03-12 14:09
I'm sorry, that sounds overcomplicated. My aim is to keep things as simple as possible, I don't want to build a whole new API.
Moreover, things like the `position` argument are not generalizable because the predicate to abort requests is arbitrary, not just based on the resource type.

> abort all request urls when their response is not <200>

The idea is to abort requests before they're sent, if they already have responses it's just not possible to abort them anymore.

However, passing the `Route` object instead of just the `Request` sounds interesting, to allow the usage of `Request.fulfill`. I'm not sure though, perhaps that could be a separate hook to keep this one simply returning a boolean.
