### ISSUE TITLE
Scrapy can't be terminated when using scrapy-playwright

### ISSUE THREAD

**Issue by nealsun** [scrapy-plugins/scrapy-playwright#169] opened 2023-02-01 11:15 UTC
Befor using scrapy-playwright, scrapy process quit after all requests crawled, but now the process can't stop, here is my log:
```
2023-02-01 11:04:51 [scrapy.utils.log] INFO: Scrapy 2.7.1 started (bot: presale)
2023-02-01 11:04:51 [scrapy.utils.log] INFO: Versions: lxml 4.9.2.0, libxml2 2.9.14, cssselect 1.2.0, parsel 1.7.0, w3lib 2.1.1, Twisted 22.10.0, Python 3.7.16 (default, Dec  8 2022, 03:54:13) - [GCC 10.2.1 20210110], pyOpenSSL 22.1.0 (OpenSSL 3.0.7 1 Nov 2022), cryptography 38.0.4, Platform Linux-5.10.47-linuxkit-x86_64-with-debian-11.5
2023-02-01 11:04:51 [scrapy.crawler] INFO: Overridden settings:
{'AUTOTHROTTLE_ENABLED': True,
 'AUTOTHROTTLE_MAX_DELAY': 30,
 'AUTOTHROTTLE_START_DELAY': 1,
 'BOT_NAME': 'presale',
 'CONCURRENT_ITEMS': 1,
 'DOWNLOAD_DELAY': 1.5,
 'FEED_EXPORT_ENCODING': 'utf-8',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'presale.spiders',
 'REQUEST_FINGERPRINTER_IMPLEMENTATION': '2.7',
 'RETRY_PRIORITY_ADJUST': -2,
 'RETRY_TIMES': 5,
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['presale.spiders'],
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor',
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'}
2023-02-01 11:04:51 [scrapy.extensions.telnet] INFO: Telnet Password: f3c680e235cb963f
2023-02-01 11:04:51 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.throttle.AutoThrottle']
2023-02-01 11:04:51 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'presale.middlewares.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2023-02-01 11:04:51 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2023-02-01 11:04:51 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2023-02-01 11:04:51 [scrapy.core.engine] INFO: Spider opened
2023-02-01 11:04:51 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2023-02-01 11:04:51 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2023-02-01 11:04:51 [scrapy-playwright] INFO: Starting download handler
2023-02-01 11:04:51 [scrapy-playwright] INFO: Starting download handler
2023-02-01 11:04:56 [redirect] INFO: start
2023-02-01 11:04:56 [scrapy.robotstxt] WARNING: Failure while parsing robots.txt. File either contains garbage or is in an encoding other than UTF-8, treating it as an empty file.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/scrapy/robotstxt.py", line 16, in decode_robotstxt
    robotstxt_body = robotstxt_body.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 248: invalid continuation byte
2023-02-01 11:05:03 [scrapy-playwright] INFO: Launching browser chromium
2023-02-01 11:05:03 [scrapy-playwright] INFO: Browser chromium launched
2023-02-01 11:05:04 [scrapy.core.engine] INFO: Closing spider (finished)
2023-02-01 11:05:04 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 3112,
 'downloader/request_count': 7,
 'downloader/request_method_count/GET': 7,
 'downloader/response_bytes': 41640,
 'downloader/response_count': 7,
 'downloader/response_status_count/200': 2,
 'downloader/response_status_count/302': 3,
 'downloader/response_status_count/404': 2,
 'elapsed_time_seconds': 13.186248,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 2, 1, 11, 5, 4, 884842),
 'httpcompression/response_bytes': 13888,
 'httpcompression/response_count': 2,
 'log_count/INFO': 19,
 'log_count/WARNING': 2,
 'memusage/max': 76832768,
 'memusage/startup': 76832768,
 'playwright/context_count': 1,
 'playwright/context_count/max_concurrent': 1,
 'playwright/context_count/non-persistent': 1,
 'playwright/page_count': 1,
 'playwright/page_count/max_concurrent': 1,
 'playwright/request_count': 29,
 'playwright/request_count/method/GET': 29,
 'playwright/request_count/navigation': 5,
 'playwright/request_count/resource_type/document': 5,
 'playwright/request_count/resource_type/font': 3,
 'playwright/request_count/resource_type/image': 4,
 'playwright/request_count/resource_type/script': 11,
 'playwright/request_count/resource_type/stylesheet': 6,
 'playwright/response_count': 26,
 'playwright/response_count/method/GET': 26,
 'playwright/response_count/resource_type/document': 5,
 'playwright/response_count/resource_type/font': 1,
 'playwright/response_count/resource_type/image': 4,
 'playwright/response_count/resource_type/script': 10,
 'playwright/response_count/resource_type/stylesheet': 6,
 'request_depth_max': 1,
 'response_received_count': 4,
 'robotstxt/request_count': 2,
 'robotstxt/response_count': 2,
 'robotstxt/response_status_count/404': 2,
 'scheduler/dequeued': 4,
 'scheduler/dequeued/memory': 4,
 'scheduler/enqueued': 4,
 'scheduler/enqueued/memory': 4,
 'start_time': datetime.datetime(2023, 2, 1, 11, 4, 51, 698594)}
2023-02-01 11:05:04 [scrapy.core.engine] INFO: Spider closed (finished)
2023-02-01 11:05:04 [scrapy-playwright] INFO: Closing download handler
```
It should close browser after download handler closed, and exit the scrapy process finally. It now stay at "Closing download handler", how to solve the problem. 

## Enviroment
docker with base image `python:3.7.16`, install playwright with `pip install --no-cache-dir  scrapy playwright && playwright install chromium && playwright install-deps chromium `

**Comment by elacuesta** [comment] 2023-02-01 17:43
This is not enough to attempt to reproduce, please provide a [minimal, reproducible example ](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by nealsun** [comment] 2023-02-02 02:07
Here is my example,
It's Spider:
```
import scrapy

class TestSpider(scrapy.Spider):
    name = "test"
    
    start_urls = [
        "https://httpbin.org/get"
    ]


    def start_requests(self):
        self.logger.info("start")
        for url in self.start_urls:
            yield scrapy.Request(url=url, 
                                 callback=self.parse,
                                 meta={"playwright": False})

            
    def parse(self, response):
        self.logger.info("finished")
```

and Settings

```
BOT_NAME = 'test'

SPIDER_MODULES = ['test.spiders']
NEWSPIDER_MODULE = 'test.spiders'

# Crawl responsibly by identifying yourself (and your website) on the user-agent
USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'

# Obey robots.txt rules
ROBOTSTXT_OBEY = True

# Configure maximum concurrent requests performed by Scrapy (default: 16)
#CONCURRENT_REQUESTS = 32

# Configure a delay for requests for the same website (default: 0)
# See https://docs.scrapy.org/en/latest/topics/settings.html#download-delay
# See also autothrottle settings and docs
DOWNLOAD_DELAY = 0.25
RANDOMIZE_DOWNLOAD_DELAY = True
# The download delay setting will honor only one of:
#CONCURRENT_REQUESTS_PER_DOMAIN = 16
#CONCURRENT_REQUESTS_PER_IP = 16

CONCURRENT_ITEMS = 1

# Disable cookies (enabled by default)
COOKIES_ENABLED = True
# COOKIES_DEBUG = True



# Enable or disable downloader middlewares
# See https://docs.scrapy.org/en/latest/topics/downloader-middleware.html
DOWNLOADER_MIDDLEWARES = {
}

# Enable or disable extensions
# See https://docs.scrapy.org/en/latest/topics/extensions.html
EXTENSIONS = {
#    'scrapy.extensions.telnet.TelnetConsole': None,
    'scrapy.extensions.throttle.AutoThrottle': 500
}

DOWNLOAD_HANDLERS = {
    "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
    "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
}

# Enable and configure the AutoThrottle extension (disabled by default)
# See https://docs.scrapy.org/en/latest/topics/autothrottle.html
AUTOTHROTTLE_ENABLED = True
# The initial download delay
AUTOTHROTTLE_START_DELAY = 1
# The maximum download delay to be set in case of high latencies
AUTOTHROTTLE_MAX_DELAY = 30
# The average number of requests Scrapy should be sending in parallel to
# each remote server
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
# Enable showing throttling stats for every response received:
AUTOTHROTTLE_DEBUG = False

# Set settings whose default value is deprecated to a future-proof value
REQUEST_FINGERPRINTER_IMPLEMENTATION = '2.7'
TWISTED_REACTOR = 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'


FEED_EXPORT_ENCODING = 'utf-8'

PLAYWRIGHT_DEFAULT_NAVIGATION_TIMEOUT = 15 * 1000

LOG_LEVEL = 'INFO'

```

and deps version:

Scrapy==2.7.1
scrapy-playwright==0.0.25

**Comment by elacuesta** [comment] 2023-02-03 01:11
This is a simple example and it works just fine, if you're having trouble running in docker you need to also provide the Dockerfile and any additional instructions to build & run.

**Comment by nealsun** [comment] 2023-02-07 02:59
[playwright_test.zip](https://github.com/scrapy-plugins/scrapy-playwright/files/10671105/playwright_test.zip)
It's a full example with docker file, just run `docker build -t playwright_test -f Dockerfile .` and `docker run playwright_test`, the container hang on `2023-02-07 02:29:29 [scrapy-playwright] INFO: Closing download handler`.
If I comment the `DOWNLOAD_HANDLERS` in settings file, then scrapy will not launch chromium, the container will exit normally after spider finished.

**Comment by elacuesta** [comment] 2023-02-07 17:44
Interesting, I can reproduce the issue now. I tracked it down the following path:
* https://github.com/scrapy-plugins/scrapy-playwright/blob/v0.0.26/scrapy_playwright/handler.py#L265
* https://github.com/microsoft/playwright-python/blob/v1.30.0/playwright/async_api/_context_manager.py#L54
* https://github.com/microsoft/playwright-python/blob/v1.30.0/playwright/_impl/_connection.py#L259
* https://github.com/microsoft/playwright-python/blob/v1.30.0/playwright/_impl/_transport.py#L105

Last one is a Future which I believe should be set [here](https://github.com/microsoft/playwright-python/blob/v1.30.0/playwright/_impl/_transport.py#L161), I suspect there might be something going on before that at `PipeTransport.run` but I didn't go that far.

scrapy-playwright uses the `PlaywrightContextManager` class this way because I need to enter & exit the context from different methods. The issue is not because of the fact that I'm awaiting `start` & `__aexit__` and not using `async with`, as the following works well: 

```python
import asyncio
from playwright.async_api import PlaywrightContextManager

async def main():
    pw_context_manager = PlaywrightContextManager()
    pw = await pw_context_manager.start()
    browser = await pw.chromium.launch()
    page = await browser.new_page()
    await page.goto("https://example.org")
    title = await page.title()
    print(f"Page title: {title}")
    await browser.close()
    await pw_context_manager.__aexit__()

if __name__ == "__main__":
    asyncio.run(main())

```

The good news is that it can be resolved by upgrading your Python base image, I tested successfully with `python:3.8.16` & `python:3.9.16`. I guess there's some incompatibility between Playwright, Twisted and the asyncio module within the Python 3.7 Docker image.

**Closed by elacuesta** 2023-02-07 17:44 UTC
